### ISSUE TITLE
NA handling

### ISSUE THREAD

**Issue by tnagler** [tnagler/VineCopula#12]
So far the estimation algorithms simply throw an error whenever NAs appear in the data. This is a reasonable solution implying that users should think of handling NAs themselves reasonably before fitting a vine. 

For fitting vines, there are cases when this is problematic. For example when you have time series of different length and want to use as much information as possible for each pair. 

My suggestion: Throw a warning, that there are NAs, but use pairwise complete data for each pair. We could also add an option that allows to switch this type of NA handling on and of.

**Comment by ulf85** [comment]
I think this is problematic. In particular, in the case you describe above it is very important to clean, adjust, filter, etc the data **before** they are fitted marginally and then put into a vine.
Time series data have to be in the same time horizont to calculate the correlation correct.
Further, if different lengths of time series are allowed peaple may run into wrong **predictions**. I have seen so many "papers" about vines whose authors do not care about margins or the correct fitting of the vine, but present the results and an interpretation of their findings which are wrong.
Do not make it too easy for all these people to throw their data in the package and get some "results".

**Comment by ulf85** [comment]
Nevertheless, NA handling is an important point and worth to think about in the context  of our package.

The user should know how NAs are treated and why. And in my opinion it is up to him/her how to treat them. For example, he/she can ignore them, impute them, etc.

**Comment by ulf85** [comment]
As we discussed today on the conference it may be a good idea to have aminimum number of observation which overlap. To calculate such a minimum number ine idea is to calculate standard errors for the Kendall's tau estimate. We have to be sure that at least such an estimate works properly.

**Comment by tnagler** [comment]
All functions in the package can now handle NAs in the data (see 6840187419d5561c25ab3022f89d1e102defa166). If the data contain NAs,  the user will receive an adequate warning message. A more detailed explanation follows below:

Evaluation functions such as `BiCopHfunc`, `RVinePDF`: The functions' output is of the same length as the input data. But when there are NAs in the input, also the output will have NAs at the same index. Example: 

``` r
> u1 <- c(0.5, NA)
> u2 <- c(0.5, 0.2)
> BiCopPDF(u1, u2, 3, 3)
#> [1] 1.845385       NA
#> Warning message:
#> In BiCopPDF: Some of the data are NA.
```

Bivariate functions related to estimation or summary statistics remove the NAs from the data and only use complete observations. Examples:

``` r
> sim <- BiCopSim(500, 3, 3)
> sim[1, 1] <- NA
> BiCopSelect(sim[, 1], sim[, 2])
#> Bivariate copula: Clayton (par = 2.95, tau = 0.6) 
#> Warning message:
#> In BiCopSelect: Some of the data are NA. Only complete observations are used. 
> BiCopVuongClarke(sim[, 1], sim[, 2], 1:3)
#>         1 2 3 13
#> Vuong  -1 1 3 -3
#> Clarke -1 1 3 -3
#> Warning message:
#>  In BiCopVuongClarke: Some of the data are NA. Only complete observations are used. 
```

Estimation of R-vine copulas always uses pairwise complete observations. If the number of complete pairwise observations is less then 10, the Independence copula is selected automatically. Example:

``` r
> data(daxreturns)
> u <- daxreturns[1:500, 1:3]
> u[1:495, 1] <- NA
> RVineStructureSelect(u)
#> C-vine copula with the following pair-copulas:
#> Tree 1:
#> 3,1  Independence 
#> 3,2  t (par = 0.6, par2 = 3.45, tau = 0.41) 
#> 
#> Tree 2:
#> 2,1;3  Independence 
#> 
#> ---
#> 1 <-> ALV.DE,   2 <-> BAS.DE,
#> 3 <-> BAYN.DE
#> Warning messages:
#> 1:  In RVineStructureSelect: Some of the data are NA. Only pairwise complete 
#> observations are used. 
#> 2:  In RVineStructureSelect: Insufficient data for at least one pair. Independence 
#> has been selected automatically. 
```

For `treecrit` equal to `"tau"` or `"rho"`, the edge weight of each pair is mupliplied by `sqrt(complete.freq)` where `complete.freq` is the proportion of complete observations in the data corresponding to that pair. The factor `sqrt(complete.freq)`  penalizes the number of NAs in the structure selection and makes pairs with lots of NAs less likely to be selected. The factor is motivated by the root-n asymptotic normality of the estimators of Kendall's tau and Spearman's rho. As a consequence,  the two criteria are statistically indistinguishable from 0 when

```
     crit                       > const * sqrt(1/n.complete)  
<=>  crit                       > const * sqrt(1/n) * sqrt(1/complete.freq)
<=>  crit * sqrt(complete.freq) > const * sqrt(1/n)
```

where `n.complete` is the number of complete observations for the pair, and `n` is the number of all observations (including NAs). The factor `sqrt(complete.freq)`  thus normalizes the edge weights such that they can all be compared to the same critical value `const * sqrt(1/n)`.

The criteria `"AIC"`, `"BIC"`, and `"cAIC"` automatically penalize the number of NAs by using only complete observations.
