### ISSUE TITLE
Parameter restrictions for Archimedean copulas

### ISSUE THREAD

**Issue by tnagler** [tnagler/VineCopula#13]
Most functions for Archimedean copulas run into numerical problems when the absolute value of Kendall's tau is close to 1. The critical value varies between families and functions. We should:
- find critical values for each family
- prevent selection algorithms from selecting a family when the corresponding critical value is exceeded
- throw warnings or errors when infeasible parameter values were specified manually.

**Comment by ulf85** [comment]
Concerning your second point: Bound for the BB copulas are already implemented. If a parameter value exceeds a certain value the selection algorithm switch to the boundery case, e.g. the Joe copula for some BB copulas.
For the first point we should have a look at our old stuff if we have already some bounds for some of the copulas.

**Comment by tnagler** [comment]
Done by ec1a00828f7b6ec8f8cd665bd36a9367fe89d873
