### ISSUE TITLE
Fix for get_family

### ISSUE THREAD

**Issue by gareth-d-ga** [tnagler/VineCopula#14]
There seems to be a bug in the family edge label names that appear in plot.RVineMatrix when using edge.labels='family'.

Apologies I haven't made a simple reproducible example, but if the get_family function is edited as below, then it seems to be fixed. 

```
get_family<-function (j, tree, RVM) {
    d <- nrow(RVM$family)
    #M <- RVM$Matrix
    #paste(RVM$family[M[d - tree + 1, j]])
    paste(RVM$family[d - tree + 1, j])
}
```

**Comment by tnagler** [comment]
Fixed by 94f213437a78fae50fe44c7d313cb59607aa4b32. Thanks!
