### ISSUE TITLE
Flexible edge weights for the tree structure selection

### ISSUE THREAD

**Issue by ulf85** [tnagler/VineCopula#17]
It may be a good idea to be more flexible in the egde weights for the tree structure stelection in the `RVineStructureSelection` function.
One sugestion by Harry Joe is to use `log(sqrt(1-rho^2))` (I hope I get it right; he will send some code and comments on that).
There can be alot of other possible weights.
Another idea is to allow the user to hand over a function for the calculation of the weights.
So the idea is to add a new argument to `RVineStructureSelect`
`RVineStructureSelect(data, weights="tau")`
`RVineStructureSelect(data, weights="logtau")`
`RVineStructureSelect(data, weights=function(u1, u2){doSomeThing(u1,u2)})`

**Comment by ulf85** [comment]
Planned for version 2.1

**Comment by tnagler** [comment]
It has now been implemented by adding an argument `treecrit` to `RVineStructureSelect` (see bd66d3bc36e4415506b25f0534c6cc6f0b9a29a0). Possible choices are 
- `"tau"`
- `"rho"`
- `"AIC"`
- `"BIC"`
- `"cAIC"`
- a custom `function(u1, u2, weights) ...` returning a numeric value.

Feel free to add (and document) more weights.
