### ISSUE TITLE
Copula diagnostics before vine selection

### ISSUE THREAD

**Issue by ulf85** [tnagler/VineCopula#18]
Some suggestions by Harry Joe: one can do some simple copula diagnostics before one selects the vine or the copula family. For example, as we already do, one estimates Kendall's tau to shrink the families to the positive or negative correlated ones. Similar with tail dependence. In particular asymmetries. Further ideas are given in a short tech report. 

Planned, if at all, for version > 2.1

**Comment by tnagler** [comment]
This was already implement in v2.0.0 (`presel = TRUE` argument).
