### ISSUE TITLE
New vine selection heuristic

### ISSUE THREAD

**Issue by ulf85** [tnagler/VineCopula#19]
There is another (new) heuristic by Harry Joe and Eike Brechmann to select a vine copula structure. 
The Main idea is the following:
Estimate all partial correlations and use them as edge weights 
The selection of the vine structure is under the assumption of normality. Thus no copula families have to be selected in the first place.
Further, no pseudo observations for the higher order trees have to be calculated since the partial correlations are given.
A Further expansion stage may be the next ideas of Joe and Brechmann:
Instead of using just the one maximum spanning tree, use the Best 10 spanning trees.
Thereby the search area is bigger. But also it growths exponantially. To avoid that there is a heuristic described in the paper.

These heuristics may be options for `RVineStructureSelect` available by an additional argument. 

There is code available by Eike.

**Comment by tnagler** [comment]
Don't think this fits in the current package. Maybe an add-on package containing various structure selection methods would be an option at some point (with all that Dominik developed).
