### ISSUE TITLE
Bug in RVineMLE?

### ISSUE THREAD

**Issue by rje42** [tnagler/VineCopula#22]
[Line 501 in `RVineMLE.R`](https://github.com/tnagler/VineCopula/blob/master/R/RVineMLE.R#L501) seems to be wrong: 

``` r
newpar2[posParams] <- out1$par[(nParams + 1):(nParams + nParams2)]
```

I think the subsetting should be on `posParams2` rather than `posParams`.  

I ran some code in which `posParams` was of length 3 but `posParams2` only of length 2, which led to a warning.

EDIT: Vaguely related: [line 513](https://github.com/tnagler/VineCopula/blob/master/R/RVineMLE.R#L513) is dangerous as there's no test that `nParams2 > 0` here.  I'd suggest replacing

``` r
(nParams + 1):(nParams + nParams2)
```

with

``` r
nParams1 + seq_len(nParams2)
```

throughout the function, as it prevents these problems.

P.S. The package is very useful, thanks for making it!

**Comment by tnagler** [comment]
Thanks for reporting the bug and the additional suggestion!
