### ISSUE TITLE
Parametr type in RVineStructureSelect and output message 

### ISSUE THREAD

**Issue by Mihail-S** [tnagler/VineCopula#38]
I have passed the parametr `type='CVine'` into the `RVineStructureSelect()` function and seen in the console `R-vine copula...`
```
RVineStructureSelect(data=empCop, family=1, type='CVine')
R-vine copula with the following pair-copulas:
```
then I have changed the parametr on `type='RVine'` and the output message is `D-vine copula...`

```
RVineStructureSelect(data=empCop, family=1, type='RVine')
D-vine copula with the following pair-copulas:
```
I hope the issue is in the text of output message  only.

**Comment by tnagler** [comment]
Thanks for reporting!

This was indeed an issue with the output message. The function `is.CVine` checks whether a structure is a C-vine, but did not work properly. Should be fixed now.
