### ISSUE TITLE
Weird results for the loglikelihood

### ISSUE THREAD

**Issue by NazBen** [tnagler/VineCopula#43]
Hi,

I'm trying to use RVineLogLik function to compute the log likelihoods of a given R-vine `RVM_target` from datasets created from different R-vines `RVM`. 

If I'm not wrong, the log likelihood should be maximum for a dataset generated from `RVM_target`. But this is not what I'm observing.

Below is an example in dimension 2 with the following figures showing the variation of the log likelihood for different parameter values and the squared gradient loglikelihood (which is null at the true dependence parameter).

Thanks for your help!

Nazih.

```
library(VineCopula)
library(ggplot2)

dim <- 2
Matrix <- c(2, 1,
            0, 1)
Matrix <- matrix(Matrix, dim, dim)

family <- c(0, 3,
            0, 0)
family <- matrix(family, dim, dim)

par <- c(0, 0.5,
         0, 0)
par <- matrix(par, dim, dim)
par2 <- matrix(0, dim, dim)

RVM_target <- VineCopula::RVineMatrix(Matrix = Matrix, family = family, par = par, par2 = par2)

n_theta <- 20
n <- 1000
loglik <- rep(NA, n_theta)
grads <- rep(NA, n_theta)
thetas <- seq(0.01, 0.99,length=n_theta)
par_new <- par
for (i in 1:n_theta){
    par_new[2, 1] <- thetas[i]
    RVM_new <- VineCopula::RVineMatrix(Matrix = Matrix, family = family, par = par_new, par2 = par2)
    data <- VineCopula::RVineSim(n, RVM_new)
    res <- VineCopula::RVineLogLik(data, RVM_target, separate = FALSE, calculate.V = FALSE)
    loglik[i] <- res$loglik
    grads[i] <- VineCopula::RVineGrad(data, RVM_target)$gradient
}
df <- data.frame(thetas, loglik, grads)


ggplot(data=df, aes(x=thetas, y=loglik)) +
    geom_point(color="red") +
    geom_smooth(color="grey40") +
    theme_bw()

ggplot(data=df, aes(x=thetas, y=grads**2)) +
    geom_point(color="red") +
    geom_smooth(color="grey40") +
    theme_bw()

```
![plt_likelihood](https://user-images.githubusercontent.com/11848905/27590984-b1738688-5b50-11e7-8409-3d8b37feccd9.png)
![plt_sq_grad_likelihood](https://user-images.githubusercontent.com/11848905/27591006-bfdfc740-5b50-11e7-80b8-6946ce2e0f3f.png)

**Comment by tnagler** [comment]
Hi Nazih, 

there seems to be a misunderstanding about the role of the likelihood. What you are saying is
> For a given model, the likelihood on a data set generated from this model should be larger than on a data set generated from another model.

This is not true. Imagine that the model's density is maximal at the point (0.5, 0.5). Then a data set where each observation is exactly (0.5, 0.5) will lead to the maximal likelihood, not a data set generated from the true model.

The correct interpretation is
> For a given data set, the true model has the highest likelihood among all possible models (in expectation).

I hope this helps.

Best,
Thomas

**Comment by NazBen** [comment]
Indeed, I was doing it wrong! 

Thank you for your help Thomas.

Best,
Nazih.
