### ISSUE TITLE
vignette

### ISSUE THREAD

**Issue by marianess** [tnagler/VineCopula#44]
Is there any chance this package will have a proper vignette with a couple of examples?

**Comment by tnagler** [comment]
There have been plans for a long time, but I have too much other things going on :/ If you have specific questions, feel free to open an issue or send me a mail.

**Comment by ulf85** [comment]
The sister package CDVine has a vignette. For the bivariate copula part you can have a look there. Most of the copula families and functionality is part of both packages.
For the vine copula part have look at our Web page [http://vine-copula.org](http://vine-copula.org)
There we have beside our papers also some slides and workshop material with examples.
As @tnagler said in his post we have plans for a vignette and collected already material for it. We need some time for it.
We are sorry that we haven't  one so far.

**Comment by tnagler** [comment]
More like "dying grandfather package CDVine" ;)

**Comment by marianess** [comment]
Thanks for your explanations and reference to the vine-copula website! Hopefully, more code examples will appear in future as the research progresses. Cheers!
