### ISSUE TITLE
Export C function to use in another package

### ISSUE THREAD

**Issue by hoanguc3m** [tnagler/VineCopula#46]
I am trying to export function Hfunc2 to use in my package.
It compiles correctly but can not link the dynamic library,
I make a reproducible package in my github 
https://github.com/hoanguc3m/TestVine
When using function Hfunc2 in 
https://github.com/hoanguc3m/TestVine/blob/master/src/vinetest.cpp
It turns an error when building the package 
```
installing to /home/hoanguc3m/R/x86_64-pc-linux-gnu-library/3.4/TestVine/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘TestVine’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/hoanguc3m/R/x86_64-pc-linux-gnu-library/3.4/TestVine/libs/TestVine.so':
  /home/hoanguc3m/R/x86_64-pc-linux-gnu-library/3.4/TestVine/libs/TestVine.so: undefined symbol: _Z6Hfunc2PiS_PdS0_S0_S0_S0_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/hoanguc3m/R/x86_64-pc-linux-gnu-library/3.4/TestVine’
* restoring previous ‘/home/hoanguc3m/R/x86_64-pc-linux-gnu-library/3.4/TestVine’

Exited with status 1.
```
you have any ideas to fix this. Thanks

**Comment by tnagler** [comment]
You need to tell the compiler [that `hfunc.h` is a C-header](https://isocpp.org/wiki/faq/mixing-c-and-cpp#include-c-hdrs-nonsystem)

**Comment by tnagler** [comment]
By the way, since you are working in C++, you might want to use [rvinecopulib](https://github.com/vinecopulib/rvinecopulib).

**Comment by hoanguc3m** [comment]
Hi Thomas,
Thank for pointing me out the difference. I refer to several sources
For example
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-to-native-routines-in-other-packages
In order for me to call C function in VineCopula package, you need to add R_RegisterCCallable.
I change the init.c like this and could make it work
```
 void R_init_VineCopula(DllInfo *dll)
 {
     R_registerRoutines(dll, CEntries, NULL, NULL, NULL);
     R_useDynamicSymbols(dll, FALSE);

     R_RegisterCCallable("VineCopula",        "Hfunc2",        (DL_FUNC) &Hfunc2);
 }
```
And by the way, thank for the new package. I wish to know that earlier. Haha

**Comment by tnagler** [comment]
Oh I wasn't even aware of that, thanks for the link. Could you try with #47 and report back if it works?

**Comment by hoanguc3m** [comment]
I have no trouble for now. Thank a lot.

**Comment by tnagler** [comment]
Just wanted to make you aware that the headers will now be in a subfolder and have to be included with `#include <VineCopula/name.h>`, see #48.

**Comment by hoanguc3m** [comment]
Thanks, I will try to reinstall to see if there is any error.
