### ISSUE TITLE
Error in variance calculation in RVineVuongTest

### ISSUE THREAD

**Issue by DrBlueberry** [tnagler/VineCopula#56]
[Line 102 in `RVineVuongTest.R`](https://github.com/tnagler/VineCopula/blob/master/R/RVineVuongTest.R#L102), the variance calculation seems incorrect:
```r
w <- 1/N * sum((Model1.ll - Model2.ll)^2) + (1/N * sum(Model1.ll - Model2.ll))^2
```
It should be 
```r
w <- 1/N * sum((Model1.ll - Model2.ll)^2) - (1/N * sum(Model1.ll - Model2.ll))^2 
```

**Comment by tnagler** [comment]
Thanks!

**Comment by DrBlueberry** [comment]
Hi tnagler,
I think it also needs a correction in front of the standarnd deviation, since the sd() function uses 1/(n-1) as denominator, but the vuong's test statistic use 1/n. You may check the one in BiCopVuongClarke.R, which is correct.
```r
w <- sd(Model1.ll - Model2.ll)
```
```r
w <- sqrt((n-1)/n)*sd(Model1.ll - Model2.ll)
```
