### ISSUE TITLE
Unexpected C-Vine Simulation Results

### ISSUE THREAD

**Issue by kkarrancsu** [tnagler/VineCopula#57]
I would like to simulate a dependence structure w/ 4 variables with a C-Vine, where C(1,2) = Clayton(Theta:2), C(1,3) = Clayton(Theta:3), C(1,4) = Clayton(Theta:4), and C(2,3|1) = Indep, C(2,4|1) = Indep, and C(3,4|1,2) = Indep.  I use the following R-code to do so:

```
>> library("VineCopula")
>> d = 4
>> dd = 6
>> fam = c(3,3,3,0,0,0)
>> par1 = c(2,3,4,0,0,0)
>> order = 1:d
>> RVM <- C2RVine(order, fam, par1)
>> U <- RVineSim(300, RVM)
```
However, when I plot the pairwise associations using
```
>> pairs(U)
```
I am surprised to find that C(2,3) for example is showing some association.  The pair-wise plot looks as follows:
[https://imgur.com/IJWXXAV](https://imgur.com/IJWXXAV)

I'm unsure why the Vine specified above is showing some association between C(2,3) and C(2,4).  The RVM variable prints out the following description:
```
> RVM
C-vine copula with the following pair-copulas:
Tree 1:
1,4  Clayton (par = 4, tau = 0.67) 
1,3  Clayton (par = 3, tau = 0.6) 
1,2  Clayton (par = 2, tau = 0.5) 

Tree 2:
2,4;1  Independence 
2,3;1  Independence 

Tree 3:
3,4;2,1  Independence 
```
which seems to be what I want.  Can you please advise how to simulate what I'm trying to achieve?  Essentially, I want pairwise dependence between node 1 and 2,3,4 and independence everywhere else.

**Comment by tnagler** [comment]
Hi. 2,3;1 = Independence does *not* imply that 2,3 are *unconditionally* independent. The dependence that you see in the scatterplot is induced by the dependence of the pairs 1,2 and 2,3.

A model satisfying your conditions can be set up with a D-vine:
``` r
library("VineCopula")
d = 4
dd = 6
fam = c(3,0,0,3,0,3)
par1 = c(2,0,0,3,0,4)
order = 1:d
RVM <- D2RVine(order, fam, par1)
```
```
> RVM
D-vine copula with the following pair-copulas:
Tree 1:
3,4  Independence 
2,3  Independence 
1,2  Clayton (par = 2, tau = 0.5) 

Tree 2:
2,4;3  Independence 
1,3;2  Clayton (par = 3, tau = 0.6) 

Tree 3:
1,4;2,3  Clayton (par = 4, tau = 0.67) 
```
Now 2,3,4 are jointly independent.

**Comment by kkarrancsu** [comment]
Thank you for the information and clarification - very helpful.

Kind Regards,
Kiran

**Comment by kkarrancsu** [comment]
Hello Thomas, 
I have run the simulation w/ the code you've specified.  Although I get different results than w/ the C-Vine, it seems that two out of three pairwise dependencies are not exactly Clayton copulas.  Here is the pairwise scatter plot I get: https://imgur.com/hYrZFpP

As you can see, the plots of the pairwise dependency between Var-1 and Var-3, and Var-1 and Var-4 do not look like Clayton copulas, where as the dependency between Var-1 and Var-2 do indeed look like a Clayton copula.  Do you have any further advice on how to model what I am trying to model w/ the VineCopula package?  The dependency structure I'm looking for can be captured w/ a correlation matrix, and simulated w/ a Gaussian copula of course where all entries of the correlation matrix are 0 except for the diagonal and the top row and last column (indicating pairwise dependency between the 1st variable and the remaining and independence elsewhere), but I'd like to substitute the Gaussian dependency w/ an Archimedean copula.  

Thank you again for your time.

**Comment by tnagler** [comment]
Yes, the two implict pairs (1, 3) and (1, 4) are not Clayton. A model that has Clayton with a fixed parameter for (1, 2), (1, 3), and (1, 4) and independence everywhere else cannot be represented by the model class in VineCopula. The Gaussian is somewhat special in that regard.

**Comment by kkarrancsu** [comment]
Thank you again for getting back to me.  If this type of modeling is not available via Vines, is it possible in any other graphical and/or probabilistic models?

**Comment by tnagler** [comment]
afaik there's no customary parametric model that can represent this type of dependence. the model may sound simple, but it's quite complex in terms of its vine copula representation (and similarly for  other parametric model clasess).
