### ISSUE TITLE
RVineStructureSelect() returns C-Vine even when specified otherwise 

### ISSUE THREAD

**Issue by eduar92** [tnagler/VineCopula#75]
Hello, 

I'am trying to fit an R-Vine model to my data using RVineStructureSelect(). I specify type=0 so an R-vine structure is selected, however it keeps returning a C-Vine. Could you please tell me what can be the reason for this and how to solve it? I am using R Studio on Windows and the latest Vine Copula package (2.4.1)

![RVineStructureSelect example](https://user-images.githubusercontent.com/83725395/117189944-12d20c80-addf-11eb-9c5f-abfc181bbce1.png)

**Comment by tnagler** [comment]
A C-vine is a special case of an R-vine, so no contradiction here. It just means that the selected R-vine happens to be an C-vine. 

For other data sets you might get "genuine" R-vines (i.e., not D- or C-vines), for example: 
``` r 
> set.seed(1)
> RVineStructureSelect(replicate(5, runif(50)))
R-vine copula with the following pair-copulas:
Tree 1:
4,2  Joe (par = 1.32, tau = 0.15) 
4,3  Independence 
5,1  Tawn  type 1 (par = 3.26, par2 = 0.13, tau = 0.12) 
5,4  Rotated Joe 90 degrees (par = -1.4, tau = -0.18) 

Tree 2:
3,2;4  Independence 
5,3;4  Independence 
4,1;5  Independence 

Tree 3:
5,2;3,4  Independence 
1,3;5,4  t (par = -0.04, par2 = 3.06, tau = -0.02) 

Tree 4:
1,2;5,3,4  Independence 

---
1 <-> V1,   2 <-> V2,   3 <-> V3,
4 <-> V4,   5 <-> V5
```
