### ISSUE TITLE
about choosing the variables of vine copula

### ISSUE THREAD

**Issue by Taalmasoud** [tnagler/VineCopula#81]
Dear Nagler

I would like to ask about how we could choose the variables to construct the vine copula? is there a specific order for the variables? or on what does it depend?

Regards

**Comment by tnagler** [comment]
How about you read the package documentation, relevant literature on structure selection, or even an elementary introduction to vine copulas first? You will find many papers and books with a simple google search or in this [review paper](https://tnagler.github.io/vine-arisa.pdf). 

In general, this is not a place to get basic education on the subject or software. You are expected to have done your own research and questions here should go beyond what can be found in information freely available on the internet.
