### ISSUE TITLE
Suggestion: Add a function that fits all copulas

### ISSUE THREAD

**Issue by dimitris93** [tnagler/VineCopula#82]
Hello. This is a suggestion/question about the package VineCopula. I have been working with the package and noticed that there is no way to fit and return all copulas. Is that right? I only see a method `BiCopSelect` that fits all copulas, but only returns the best fit based on AIC. What about returning all copulas, sorted on AIC? Or any chosen criterion for that matter.

I wrote a function myself called [BiCopFitAll](https://github.com/dimitris93/VineCopula/blob/master/R/BiCopSelect.R#L278)  and added in it [R/BiCopSelect.R](https://github.com/dimitris93/VineCopula/blob/master/R/BiCopSelect.R). It is a simple modification of the `BiCopSelect` function. I believe that the code is correct, but I haven't tested it very thoroughly yet. 

If there is a method to achieve such a thing, without having to extend the package, please let me know. I tried doing something similar using `VineCopula:::`, but it did not work. I see no other option other than modifying the package.

**Comment by tnagler** [comment]
It seems like [`BiCopEstList`](https://tnagler.github.io/VineCopula/reference/BiCopEstList.html) is what you are looking for.

**Comment by dimitris93** [comment]
I must have missed this function. Thanks a lot
