### ISSUE TITLE
Parameter - error given for rotated Gumbel and Clayton copulas

### ISSUE THREAD

**Issue by simbrant** [tnagler/VineCopula#84]
The following code produces the errors 

"
Error: 
 In VineCopula::BiCopDeriv: The parameter of the rotated Clayton copula has to be be in the interval [-28,0)
" 
and, 
"
Error: 
 In VineCopula::BiCopDeriv: The parameter of the rotated Gumbel copula has to be in the interval [-17,-1].
"

u <- cbind(runif(100), runif(100))

VineCopula::BiCopDeriv(
  u[, 1], u[, 2], "33", 
  par = -1)

VineCopula::BiCopDeriv(
  u[, 1], u[, 2], "23", 
  par = -1)

VineCopula::BiCopDeriv(
  u[, 1], u[, 2], "34", 
  par = -5)

VineCopula::BiCopDeriv(
  u[, 1], u[, 2], "24", 
  par = -5)

**Comment by tnagler** [comment]
The family argument should be passed as number (like `23`), not character (like `"23"`). I'll add better error messages for the next version of the package.
