### ISSUE TITLE
Regarding the utilization of copula families 

### ISSUE THREAD

**Issue by asattarii** [tnagler/VineCopula#86]
Hello,
When I am going to assign mycop <- surClaytonCopula(c(1,1)), I face this error"This functionality  is deprecated in 'VineCopula'. Use the package 'VC2copula' instead."  However, it seems that the command in "VC2copula"package and the "VineCopula" package are the same. Could you please help me with how should I use these features in assigning the copula function?

**Comment by tnagler** [comment]
Please use the function through the VC2copula package. If necessary, you can make this explicit by calling `mycop <- VC2copula::surClaytonCopula(..)`  etc.

**Comment by asattarii** [comment]
Thank you so much.
