### ISSUE TITLE
 Is there a substitute function for CDVine:: CDVineSeqEst?

### ISSUE THREAD

**Issue by HEY745** [tnagler/VineCopula#89]
Hi. I would like to create a C-vine structure.In every trees,I use  VineCopula::BiCopVuongClarke and BiCopSelect function  to select  the pair-copula families.
```
VineCopula::BiCopVuongClarke(pfv2,pfv1,familyset = c(0:10, 13, 14, 17:20))
VineCopula::BiCopSelect(pfv2,pfv1,familyset = c(0:10, 13, 14, 16:20))$family  
```
Then use CDVine::CDVineSeqEst function e to estimates the pair-copula parameters of d-dimensional C-vine copula models.
```
Tree<-data.frame(pfv2,pfv1,pfv3,mvm_cdf1,mvm_cdf2,vm_cdf3,mvm_cdf4,mvm_cdf5)
family<-c(16,1,5,5,0,0,0,16,1,5,36,23,0,5,36,13,33,0,1,0,13,0,0,0,26,0,6,0)
seqPar<- CDVineSeqEst(Tree, family = family, 1, method = "mle")
```
However, this won't work:
```
Error in BiCopEst(v[j - 1, 1, ], v[j - 1, i + 1, ], w[j, i], method, se,  : 
  Rotated Joe copula cannot be used for positively dependent data.
```
I think there's no problem with the families calculated by VineCopula. Perhaps the CDVine version is low? 
Should I convert CVine to RVine for calculation (use VineCopula::RVineSeqEst) or is there a function that can directly calculate CVine? I hope that the final copula structure is C-Vine.
This has been bothering me for a long time. Can you please advise how to do? Thanks a lot.

**Comment by tnagler** [comment]
Hi.
1. The CDVine package has been removed from CRAN 3 years ago, and there was a warning message that this package is no longer maintained years before. Please stop using it. And also don't report issues with it here, this is the VineCopula repository.
2. You already mention the more RVineSeqEst function in VineCopula. There is also another function [`C2RVine()`](https://rdrr.io/cran/VineCopula/man/C2RVine.html) that let's you use essentially the same syntax as before. If there's an issue with these functions, I'm happy to look into it. But make sure to provide a code example that I can run myself to see what's going on.

**Comment by HEY745** [comment]
I've solved my problem .Thank you.^_^
