### ISSUE TITLE
"BB8" transform to family number not present in BiCopName

### ISSUE THREAD

**Issue by gjacqueminFR** [tnagler/VineCopula#91]
Hello,
I was looking into the BiCopName function, and I noticed that the transform from the name to the family number was not implemented for the "BB8" copula. Could you please explain me why, or was that forgotten ?

I think it should be between lines 296 and 297 in the BiCopName.R file :
```
if (family == "BB6" || family == "BB6")
            fam <- 8
if (family == "BB7" || family == "BB7")
            fam <- 9
if (family == "SC" || family == "Survival Clayton")
            fam <- 13
```

Thank you for your answer !

**Comment by tnagler** [comment]
seems like it was forgotten, good catch!

**Comment by gjacqueminFR** [comment]
Nice, thank you for your help !
