### ISSUE TITLE
How to predict under specified conditions using vine copula

### ISSUE THREAD

**Issue by HEY745** [tnagler/VineCopula#93]
Hi,I have bulit a three demensions Vine Copula（variables are **x**, **y**, **z**).Then I am trying to predict **z** when **x** and **y** are set,using RVineSim function.However,the results are that only **x** (when placed in the first column of the matrix) is fixed,and **y** has changed.
![批注](https://github.com/tnagler/VineCopula/assets/144755320/696f4e52-3077-4598-aafc-24dc29aa3cb8)
![批注](https://github.com/tnagler/VineCopula/assets/144755320/47835c49-d922-4894-aea9-59b454f1e81b)
Is there any way to calculate **z** with specific values for **x** and **y**?or,is this impossible and a deficiency of Vine Copula?
Thanks a lot!

**Comment by tnagler** [comment]
This is not how you simulate conditionally from a vine, you need to do a forward Rosenblatt transform first (function `RVinePIT`). See for example [this article](https://github.com/vinecopulib/rvinecopulib/issues/269), Section 4.2.

**Comment by HEY745** [comment]
Thank you! That's really kind of you! I will try it.
