### ISSUE TITLE
pairs.copuladata

### ISSUE THREAD

**Issue by oezgesahin** [tnagler/VineCopula#96]
Hey,
The plotting function [pairs.copuladata](https://github.com/tnagler/VineCopula/blob/6519f4150093bb2c4bb122e8e37a9b97fc930078/R/pairs.R#L92) looks so inconsistent that I couldn't track the reason well. When I simulated 3D data from rotated copulas and visualized pairs plots, the lower diagonal contour plots seemed to be in the wrong direction. On the other hand, when I simulated similarly in 2D, the upper diagonal was wrong in this case. The same issue seems to apply in the [pairs_copula_data](https://github.com/vinecopulib/rvinecopulib/blob/d8a1e0fb5aba0889324b91df1323cc9cfda70d7f/R/pairs_copula_data.R#L18). Can you check below?

```
set.seed(1)
Matrix <- c(1, 2, 3,
            0, 2, 3, 
            0, 0, 3)
Matrix <- matrix(Matrix, 3, 3)
family <- c(0, 34, 34,
             0, 0, 34, 
             0, 0, 0)
family <- matrix(family,3, 3)
par <- c(0, -3, -3,
         0, 0, -3, 
         0, 0, 0)
par <- matrix(par, 3, 3)
par2 <- matrix(0, 3, 3)

RVM <- RVineMatrix(Matrix = Matrix, family = family,
                   par = par, par2 = par2,
                   names = c("V1", "V2", "V3"))

simdata <- RVineSim(300, RVM)
pairs.copuladata(simdata)

u13 <- BiCopSim(500, 34, -3)
pairs.copuladata(u13)
```

[case2.pdf](https://github.com/user-attachments/files/17599063/case2.pdf)
[case1.pdf](https://github.com/user-attachments/files/17599064/case1.pdf)

**Comment by tnagler** [comment]
That looks correct to me. The axes are flipped when you go from above to below the diagonal. This is the same behavior as in `pairs()` from base R.

**Comment by oezgesahin** [comment]
I was initially confused by the inconsistency in the lower-dimensional representation of the given data. However, I now understand that it might also change the axes if I'm not careful with the labeling. All is good; thanks!
